/*
 * YunX (云析) - A network drive share-link parser and high-speed downloader for Android.
 * Copyright (C) 2026 CYQawa
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

plugins {
    // Plugins automatically generated by MLGradleWriter.kt
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)

    alias(libs.plugins.ksp)
}

// ---- 发布签名：CI 从 GitHub Secrets 注入，本地（没有这些变量时）构建未签名包 ----
// 四项环境变量齐备且证书文件真实存在，才注册 release 签名配置：
//   YUNX_KEYSTORE_FILE      证书文件路径（.github/workflows/build-apk.yml 把 secrets.KEYSTORE_BASE64 解码到 $RUNNER_TEMP）
//   YUNX_KEYSTORE_PASSWORD  密钥库口令
//   YUNX_KEY_ALIAS          密钥别名
//   YUNX_KEY_PASSWORD       密钥口令
// 缺任意一项（本地开发、ci.yml 的编译校验）⇒ release 的 signingConfig 为 null，
// 产物是 app-release-unsigned.apk，本地不需要任何配置就能 `assembleRelease`；
// 想在本地出正式签名包，自己导出这四个变量再构建即可（证书别提交进仓库，.gitignore 已挡 *.jks）。
val releaseKeystorePath: String? = System.getenv("YUNX_KEYSTORE_FILE")?.takeIf { it.isNotBlank() }
val releaseSigningReady: Boolean = releaseKeystorePath != null &&
    file(releaseKeystorePath).isFile &&
    !System.getenv("YUNX_KEYSTORE_PASSWORD").isNullOrBlank() &&
    !System.getenv("YUNX_KEY_ALIAS").isNullOrBlank() &&
    !System.getenv("YUNX_KEY_PASSWORD").isNullOrBlank()

android {
    namespace = "com.yunx.app"
    compileSdk = 36

    defaultConfig {
        applicationId = "com.yunx.app"
        // minSdk 24：AGP 8.13 的 D8 在 minSdk < 24 时必须脱糖接口静态方法，它把接口的 $default 桥方法
        // （如 RowScope.weight$default）搬进 $-CC 伴生类，却不改写第三方库字节码里的调用点，
        // 未混淆（debug）的包渲染 README 表格时必崩 NoSuchMethodError；24 起系统原生支持，不再脱糖。
        // 原因与实测证据见 Agent.md §3.11，勿降回 23。
        minSdk = 24
        targetSdk = 34
        versionCode = 12
        versionName = "1.2.8"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        getByName("debug") {
            storeFile = file("../debug.keystore")
            storePassword = "android"
            keyAlias = "androiddebugkey"
            keyPassword = "android"
        }
        // 正式发布签名：只在环境变量齐备时注册（CI nightly 走这里；本地不注册，见文件顶部说明）。
        // 签名方案交给 AGP 按 minSdk 决定（minSdk 24 ⇒ v2 即可，不再显式开关 v1/v2，避免 API 变更踩坑）。
        if (releaseSigningReady) {
            create("release") {
                storeFile = releaseKeystorePath?.let { file(it) }
                storePassword = System.getenv("YUNX_KEYSTORE_PASSWORD")
                keyAlias = System.getenv("YUNX_KEY_ALIAS")
                keyPassword = System.getenv("YUNX_KEY_PASSWORD")
            }
        }
    }

    buildTypes {
        debug {
            signingConfig = signingConfigs.getByName("debug")
        }
        // Release 变体：R8 代码混淆 + 资源压缩瘦身（未使用的代码/资源裁剪）。
        // 签名：有发布证书就用正式签名（CI nightly / 本地自行导出变量），否则不签名 ⇒
        // 产物为 app-release-unsigned.apk（本地与 ci.yml 的编译校验都是这条路，不影响构建成功）。
        // R8 可能误删反射/序列化类，已在 proguard-rules.pro 补 Room 等 keep 规则。
        getByName("release") {
            isMinifyEnabled = true
            isShrinkResources = true
            signingConfig = if (releaseSigningReady) signingConfigs.getByName("release") else null
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }

    buildFeatures {
        compose = true
    }

    testOptions {
        // 单元测试中 android.util.Log 等桩方法返回默认值（否则一调用就抛 "Stub!"）
        unitTests.isReturnDefaultValues = true
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlin {
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.fromTarget("17"))
        }
    }
}

dependencies {
    implementation("androidx.compose.material:material-icons-extended")
    implementation("androidx.lifecycle:lifecycle-viewmodel-ktx:2.8.7")
    implementation("androidx.lifecycle:lifecycle-viewmodel-compose:2.8.7")
    implementation("com.squareup.okhttp3:okhttp:4.12.0")
    implementation(libs.material)   // 原 libs.material.color.utilities -> 改为官方 Material 主库（含 color.utilities 包）

    // Gopeed 内置下载引擎：gomobile 生成的 Java 桥接类（com/gopeed/libgopeed + go，合计 12 KB），
    // 只为编译期拿到 Libgopeed / InvokeResultListener 等类型定义；真正的引擎
    // libgojni.so（56 MB）不进仓库、不进 APK，由设置页导入 AAR 后运行时解出并 System.load。
    // 来源：libgopeed-arm64-v8a.aar 内的 classes.jar（原样拷贝，未做任何修改）。
    implementation(files("libs/gopeed-classes.jar"))

    implementation(libs.room.runtime)
    implementation(libs.room.ktx)          // 提供协程扩展，如 Flow、suspend
    ksp(libs.room.compiler)

    // GitHub README 的 GFM 渲染（表格/嵌套列表/代码高亮/折叠/图片）
    implementation(libs.markdownRenderer)

    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.activity.compose)
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.ui)
    implementation(libs.androidx.ui.graphics)
    implementation(libs.androidx.ui.tooling.preview)
    implementation(libs.androidx.material3)
    testImplementation("junit:junit:4.13.2")
    // 设置页目录选择器仪器测试：runner / JUnit 集成；Compose 测试库版本对齐现有 BOM
    androidTestImplementation("androidx.test:runner:1.6.2")
    androidTestImplementation("androidx.test.ext:junit:1.2.1")
    androidTestImplementation(platform(libs.androidx.compose.bom))
    androidTestImplementation("androidx.compose.ui:ui-test-junit4")
    debugImplementation(libs.androidx.ui.tooling)
    debugImplementation(libs.androidx.ui.test.manifest)

    // 强制 kotlin-stdlib 与项目 Kotlin 2.1.0 对齐，避免第三方库（如 mikepenz）
    // 传递引入更高版本 stdlib 导致 "compiled with an incompatible version of Kotlin"。
    constraints {
        implementation("org.jetbrains.kotlin:kotlin-stdlib:2.1.0")
    }
}